### PR TITLE
Milestone-#2: Creating the user interface

### PR DESCRIPTION
**Pull request by leonmezu1**
## Milestone 2: Creating the user interface for the Tic-Tac-Toe Ruby OOP project

In this Milestone  my development objectives are: 

- Create a first approach user interface.
- Show the game instructions to the player
- Show how the board will look and some of the interactions to play.

### CODE REVIEW

**Review by Forison — CHANGES_REQUESTED** [review]
# Hi  Leonardo👏,
you have done a good job so far😇.
Here are a few things we have to do to get this project approved🙂,
* [ ] Game tells which player turn it is. currently, the game just says it is your turn but does not tell whose turn it is actually.
* [ ] Game asks player to select from available moves.
* [ ] Game displays board after player move
* [ ] Game informs player if selected move is a winning move
* [ ] Game informs player if selected move is a draw move
* [ ] Game repeats all actions for next player's move
Find hints about these  ([screenshot hint](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/logic.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))

### `[OPTIONAL]` 
- Game ask players for their names
- we can include how to select spots on the grid in our instruction
## That is it go ahead and make these changes and submit code for review
### Happy coding
Addo Forison

**Comment by leonmezu1** [comment]
Hey back! I've worked on the requirements above:

* [x] Game tells which player turn it is. currently, the game just says it is your turn but does not tell whose turn it is actually.
* [x] Game asks player to select from available moves.
* [x] Game displays board after player move
* [x] Game informs player if selected move is a winning move
* [x] Game informs player if selected move is a draw move
* [x] Game repeats all actions for next player's move

For the second requirement the game will show the available spots if the user chooses a wrong option.

Also, the optional fixes are covered too 😁

**Review by Redvanisation — CHANGES_REQUESTED** [review]
# Changes required  ♻️ 

The project should have the following: 

* [ ] Basic game flow is prepared, [snapshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/logic.png).
  * [ ] **`[OPTIONAL]`** game ask players for their names
  * [ ] `[REQUIRED]` game tells which player turn it is
  * [ ] `[REQUIRED]` game asks player to select from available moves
  * [ ] `[REQUIRED]` game informs player if selected move is invalid
  * [ ] `[REQUIRED]` game displays board after player move
  * [ ] `[REQUIRED]` game informs player if selected move is a winning move
  * [ ] `[REQUIRED]` game informs player if selected move is a draw move
  * [ ] `[REQUIRED]` game repeats all actions for next player's move

### _After making the required changes please submit a new code review request_

### Good luck! 🍀

**Comment by leonmezu1** [comment]
I'm pretty sure I've worked in those requirements.

**Review by Redvanisation — APPROVED** [review]
# Milestone approved ✔️ 

### _Nice work on this milestone, it seems that you have met the requirements so I am approving your project. 👍_ 

### You may merge to master and submit a project completion form. 🚀 

### Good luck! 🍀

**Comment by leonmezu1** [comment]
Merge approved by TSE

**Pull request merged**
